#!/usr/bin/env ruby

$LOAD_PATH.unshift File.expand_path('../../lib', __FILE__)
require 'rspiderx'

Rspiderx.run(
  modules: {
    mediator: 'simple',
    fetcher: 'simple',
    parser: 'regex',
    crawler: 'simple',
    queue: 'memory',
    consumers: ['printer'],
    feeder:    'simple'
  },
  input:      'https://twitter.com/laithshadeed'
)
